###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "note with a user",
  "important": "false"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOjMsImlhdCI6MTc3NTM0ODM2NiwiZXhwIjoxNzc1MzQ4NTQ2fQ.D65leHGuJHy-QtuerbGqY789_MLcpZ8twV_XrdUnqSs

{
  "content": "oops",
  "important": "true"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjEsImlhdCI6MTc3NTM0ODI2OSwiZXhwIjoxNzc1MzQ4NDQ5fQ.Jn0Ky-yM1fiRmAoWVFaPS1r5BTcnesoubXAxBKZ1hFs

{
  "content": "MongoDB is webscale",
  "important": "false"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjEsImlhdCI6MTc3NTM0ODI2OSwiZXhwIjoxNzc1MzQ4NDQ5fQ.Jn0Ky-yM1fiRmAoWVFaPS1r5BTcnesoubXAxBKZ1hFs

{
  "content": "I am thirsty",
  "important": "true"
}

###
GET http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes/777

###
PUT http://localhost:3001/api/notes/3
Content-Type: application/json

{
  "important": "true"
}

###
DELETE http://localhost:3001/api/notes/5

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "user1",
  "name": "Random User1"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "jakousa",
  "name": "Jami Kousa (The Docker Captain)"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ousa",
  "name": "Outi Savolainen"
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mluukkai",
  "password": "secret"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "user1",
  "password": "secret"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "jakousa",
  "password": "secret"
}

###
PUT http://localhost:3001/api/users/jakousa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjEsImlhdCI6MTc3NTQ1MjIyMCwiZXhwIjoxNzc1NDUyNDAwfQ.XDir6p-cBLwXEamSFPDRwxYcczZRJ-dACGoFk6Va7DQ
Content-Type: application/json

{
  "disabled": false
}