###
DELETE http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpbm8xIiwiaWQiOjMsImlhdCI6MTc3NTc4MDM3Mn0.xJR_05woyvasTj4HoBtQF_vOaVaPMgeM7xW-7Ix1Ct0