GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author0",
  "url": "https://google.com",
  "title": "blog0"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author1",
  "url": "https://naver.com",
  "title": "blog1"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author2",
  "url": "https://daum.net",
  "title": "blog2"
}

###
DELETE http://localhost:3001/api/blogs/4