###
POST http://localhost:3001/api/readinglists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjIsImlhdCI6MTc3NTYzMTE1OCwiZXhwIjoxNzc1NjMxMzM4fQ.9ETKid73EieasU1zGGCSBsP7y71i__JAWDt_Aey2FCA
Content-Type: application/json

{
  "blogId": 5
}

###
POST http://localhost:3001/api/readinglists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjEsImlhdCI6MTc3NTYzMTMzMiwiZXhwIjoxNzc1NjMxNTEyfQ.UqGjtCUglfDIo8cmVD1ex0ORTVw4dpCM5vwO-tpUIRI
Content-Type: application/json

{
  "blogId": 5
}

###
PUT http://localhost:3001/api/readinglists/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjIsImlhdCI6MTc3NTYzNTQ3OSwiZXhwIjoxNzc1NjM1NjU5fQ.9R3_Uofv91le6Ux8wL-2B8Dz3uG9ZUshk4iI4Y5UrKI
Content-Type: application/json

{
  "read": true
}