GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author0",
  "url": "https://google.com",
  "title": "blog0"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author1",
  "url": "https://naver.com",
  "title": "blog1"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author2",
  "url": "https://daum.net",
  "title": "blog2"
}

###
DELETE http://localhost:3001/api/blogs/4

###
PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
  "likes": 123
}

### throws error
PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
  "likes": "hello"
}

### throws error
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author4"
}

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjcsImlhdCI6MTc3NTI0NDAyMiwiZXhwIjoxNzc1MjQ0MjAyfQ.Jv0yOkWlBCKgSePDztbWLaQ20U2DyK_ZPTLFsr_yLyI
Content-Type: application/json

{
  "author": "Lee Kang-in",
  "url": "https://espn.com",
  "title": "Son Heung-min scores"
}