###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkai",
  "email": "mluukkai@gmail.com",
  "password": "secret"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "sonny",
  "name": "Son Heung-min",
  "email": "spurs7@spurs.com",
  "password": "sonny"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "dino1",
  "name": "T-Rex",
  "email": "spurs7@spurs.com",
  "password": "dino"
}

###
GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/1

###
GET http://localhost:3001/api/users/2

###
GET http://localhost:3001/api/users/2?read=false

###
GET http://localhost:3001/api/users/2?read=true

###
GET http://localhost:3001/api/users/mluukkai

###
GET http://localhost:3001/api/users/sonny

###
PUT http://localhost:3001/api/users/mluukkai
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjYsImlhdCI6MTc3NTE3OTk0NCwiZXhwIjoxNzc1MTgwMTI0fQ.xe3TfDU082YgrPW47woMh9IlkbLP9xxwIrrPhj8XMdE

{
  "name": "John Doe"
}

###
PUT http://localhost:3001/api/users/mluukkai/disable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjEsImlhdCI6MTc3NTcwMDA4NywiZXhwIjoxNzc1NzAwMjY3fQ.wBTHumRNLnIcOiI5jYGQWJE09IhqnBN_l7XcFIbS5eE

{
  "disabled": true
}