GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author0",
  "url": "https://google.com",
  "title": "blog0"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author1",
  "url": "https://naver.com",
  "title": "blog1"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author2",
  "url": "https://daum.net",
  "title": "blog2"
}

###
DELETE http://localhost:3001/api/blogs/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjYsImlhdCI6MTc3NTI0NTI5OCwiZXhwIjoxNzc1MjQ1NDc4fQ.P6JqoRQiUB8UzibmzBzZOEYDVixdrxdAnDf6507vTOU

###
PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
  "likes": 123
}

### throws error
PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
  "likes": "hello"
}

### throws error
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author4"
}

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjYsImlhdCI6MTc3NTI0NTA1MCwiZXhwIjoxNzc1MjQ1MjMwfQ.4EeE9EZCf_b5oLKZ_WPDhizyi8IsVdau0ql-VuPIdPQ
Content-Type: application/json

{
  "author": "Mikel Arteta",
  "url": "https://mooc.fi",
  "title": "Welcome new students"
}

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjcsImlhdCI6MTc3NTMzMzY2OSwiZXhwIjoxNzc1MzMzODQ5fQ.NzPz0BQTSgxPAUQKPDYLpnvXRw0N8KBeSEWJt1l2UzM
Content-Type: application/json

{
  "author": "Mikel Arteta",
  "url": "https://microsoft.com",
  "title": "Typescript generics",
  "likes": 333
}

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjcsImlhdCI6MTc3NTMzMzY2OSwiZXhwIjoxNzc1MzMzODQ5fQ.NzPz0BQTSgxPAUQKPDYLpnvXRw0N8KBeSEWJt1l2UzM
Content-Type: application/json

{
  "author": "Mikel Arteta",
  "url": "https://mooc.fi",
  "title": "How to succeed in completing courses",
  "likes": 200
}

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjIsImlhdCI6MTc3NTYxNjUzOSwiZXhwIjoxNzc1NjE2NzE5fQ.PY8VGnEXgY4IJAzdvtMpVpeNfdLdbY9fOOEKWXzTwX4
Content-Type: application/json

{
  "author": "Fabrizio Romano",
  "url": "https://x.com/fabrizioromano",
  "title": "Here we go!"
}

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbm55IiwiaWQiOjIsImlhdCI6MTc3NTYxNjUzOSwiZXhwIjoxNzc1NjE2NzE5fQ.PY8VGnEXgY4IJAzdvtMpVpeNfdLdbY9fOOEKWXzTwX4
Content-Type: application/json

{
  "author": "Fabrizio Romano",
  "url": "https://x.com/fabrizioromano",
  "title": "Deal confirmed",
  "year": 2023,
  "likes": 111
}