### for prod and dev server
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "abc12345",
  "name": "Harry Potter",
  "password": "123abcDe@"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "admin",
  "name": "admin",
  "password": "Q1w2e3r4!"
}

### for test server
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user",
  "name": "user",
  "password": "Q1w2e3r4!"
}