name: Deployment pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: part11

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e

  deploy:
    needs: [build_and_test]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  discord_notify_success:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ''), '#discord') }}
    runs-on: ubuntu-latest
    steps:
      - name: trigger success notification
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "✅ **Deployment Successful!** A new version deployed to production"
          title: "Deployment Details"
          status: ${{ job.status }}
          nodetail: true
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}

  discord_notify_failure:
    needs: [deploy]
    if: ${{ always() && github.event_name == 'push' && needs.deploy.result == 'failure' && contains(join(github.event.commits.*.message, ''), '#discord') }}
    runs-on: ubuntu-latest
    steps:
      - name: trigger failure notification
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "❌ **Build Failed!** The pipeline encountered an error"
          title: "Failure Details"
          status: failure
          nodetail: true
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}

            [[View Commit]](${{ github.event.head_commit.url }})
            [[View Workflow Run]](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
